[package]
name = "svg_tools"
version = "0.1.0"
edition = "2021"



[dependencies]
tiny-skia = "0.11"
usvg = "0.42"
resvg = "0.42"
png = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
xmltree = "0.10"

common_types = { path = "../structs" }

roxmltree = "0.21.1"